<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.analyzers" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Crownfall.Sim/Crownfall.Sim.csproj" />
  </ItemGroup>
</Project>
